services:
  server:
    image: node:18
    container_name: bookstore
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm start -- --legacy-watch"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: book-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookdb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"


#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    restart: always
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "8080:80"
#    depends_on:
#      - db

volumes:
  db_data: